BEGIN;
CREATE TABLE public.users(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(50) NOT NULL,
    created_date date, 
    is_active boolean, 
    email character varying(255) NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);
CREATE TABLE public.jobseekers( 							   
    user_id integer NOT NULL,
    first_name character varying(60) NOT NULL,
    last_name character varying(60) NOT NULL,
    nationality_id character varying(11) NOT NULL,
    is_verified boolean NOT NULL,
    birth_date date NOT NULL,
    CONSTRAINT pk_jobseekers PRIMARY KEY (user_id), 
	CONSTRAINT fk_jobseekers_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);
CREATE TABLE public.employees(
    user_id integer NOT NULL,
    first_name character varying(60) NOT NULL, 
    sur_name character varying(60) NOT NULL,
    CONSTRAINT pk_employees PRIMARY KEY (user_id),
	CONSTRAINT fk_employees_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);
CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    phone_no character varying(25) NOT NULL,
    is_verified boolean NOT NULL,
    company_name character varying(250) NOT NULL,
    web_address character varying(255),
    CONSTRAINT pk_employers PRIMARY KEY (user_id),
	CONSTRAINT fk_employers_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);
CREATE TABLE public.verification_codes(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    code character varying(50),
    is_confirmed boolean,
    created_date date,
    is_active boolean, 
    CONSTRAINT pk_verification_codes PRIMARY KEY (id),
	CONSTRAINT fk_verification_codes_users FOREIGN KEY(user_id) REFERENCES public.users(id)
);
CREATE TABLE public.employees_activation_employers(
    id integer NOT NULL,
    employer_id integer,
    employee_id integer,
    CONSTRAINT pk_employers_activation_employees PRIMARY KEY (id),
	CONSTRAINT fk_employees_activation_employees_employers FOREIGN KEY(employer_id) REFERENCES public.employers(user_id),
	CONSTRAINT fk_employees_activation_employees_employees FOREIGN KEY(employee_id) REFERENCES public.employees(user_id)
);
CREATE TABLE public.cities(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50),
    created_date date,
    CONSTRAINT pk_cities PRIMARY KEY (id)
);
CREATE TABLE public.job_titles(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(250),
    created_date date,
    is_active boolean,
    CONSTRAINT pk_job_titles PRIMARY KEY (id)
);
CREATE TABLE public.job_advertisements( 
    id integer NOT NULL,
    created_date date NOT NULL,
    deadline date NOT NULL,
    description character varying(255) NOT NULL, 
    is_open boolean NOT NULL,
    open_title_count integer NOT NULL,
    salary_max integer,
    salary_min integer,
    city_id integer NOT NULL,
    employer_id integer NOT NULL, 
    job_title_id integer NOT NULL,
    published_at date NOT NULL,
    is_active boolean NOT NULL,
    CONSTRAINT pk_job_advertisements PRIMARY KEY (id),
	CONSTRAINT fk_job_advertisements_cities FOREIGN KEY(city_id) REFERENCES public.cities(id),
	CONSTRAINT fk_job_advertisements_employers FOREIGN KEY(employer_id) REFERENCES public.employers(user_id),
	CONSTRAINT fk_job_advertisements_job_titles FOREIGN KEY(job_title_id) REFERENCES public.job_titles(id)
);
CREATE TABLE public.resume_main(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    jobseeker_id integer NOT NULL,
    github_link character varying(220),
	linkedin_link character varying(220), 
	created_date date NOT NULL,
    is_active boolean NOT NULL,
	cover_letter character varying(350), 
    resume_title character varying(220),
    CONSTRAINT pk_resume_main PRIMARY KEY (id),
	CONSTRAINT fk_resume_main_jobseekers FOREIGN KEY(jobseeker_id) REFERENCES public.jobseekers(user_id)
);
CREATE TABLE public.schools(
	id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	school_name CHARACTER VARYING(220) NOT NULL,
	city_id int NOT NULL,
	status boolean NOT NULL,
	CONSTRAINT pk_schools PRIMARY KEY (id),
	CONSTRAINT uc_schools UNIQUE(school_name), 
	CONSTRAINT fk_schools_cities FOREIGN KEY(city_id) REFERENCES public.cities(id)
);
CREATE TABLE public.resume_educations( 
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resume_main_id integer NOT NULL,
    school_id integer NOT NULL,
    department character varying(220) NOT NULL,
    started_date date,
    ended_date date,
    created_date date,
    is_active boolean,
   CONSTRAINT pk_resume_educations PRIMARY KEY (id),
	CONSTRAINT fk_resume_educations_resume_main FOREIGN KEY(resume_main_id) REFERENCES public.resume_main(id),
	CONSTRAINT fk_resume_educations_schools FOREIGN KEY(school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.resume_experiences(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resume_main_id integer NOT NULL,
    company_name character varying,
    position character varying,
    started_date date,
    ended_date date, 
    created_date date,
    is_active boolean,
   CONSTRAINT pk_resume_experiences PRIMARY KEY (id),
	CONSTRAINT fk_resume_experiences_resume_main FOREIGN KEY(resume_main_id) REFERENCES public.resume_main(id)
);
CREATE TABLE public.resume_images(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resume_main_id integer NOT NULL, 
    url_address character varying(220),
    is_active boolean, 
    created_date date,
    CONSTRAINT pk_resume_images PRIMARY KEY (id),
	CONSTRAINT fk_resume_images_resume_main FOREIGN KEY(resume_main_id) REFERENCES public.resume_main(id)
);
CREATE TABLE public.resume_languages(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resume_main_id integer NOT NULL,
    language_name character varying(220) NOT NULL,
    level integer NOT NULL,
    created_date date, 
    is_active boolean,
    CONSTRAINT pk_resume_languages PRIMARY KEY (id),
	CONSTRAINT fk_resume_languages_resume_main FOREIGN KEY(resume_main_id) REFERENCES public.resume_main(id)
);
CREATE TABLE public.skill_categories(
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	category_name CHARACTER VARYING(50) NOT NULL,
	is_active boolean NOT NULL,
	CONSTRAINT pk_skill_categories PRIMARY KEY(id),
	CONSTRAINT uc_skill_categories UNIQUE(category_name)
);
CREATE TABLE public.resume_skills(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    resume_main_id integer NOT NULL,
    skill_name character varying(220) NOT NULL,
	category_id int NOT NULL,
    created_date date,
    is_active boolean,
    CONSTRAINT pk_resume_skills PRIMARY KEY (id),
	CONSTRAINT fk_resume_skills_resume_main FOREIGN KEY(resume_main_id) REFERENCES public.resume_main(id), 
	CONSTRAINT fk_resume_skills_skill_categories FOREIGN KEY(category_id) REFERENCES public.skill_categories(id)
);
CREATE TABLE public.verification_codes(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    code character varying(50) NOT NULL,
    is_confirmed boolean NOT NULL, 
    created_date date NOT NULL,
    is_active boolean NOT NULL, 
	confirm_date date NOT NULL,
    CONSTRAINT pk_verification_codes PRIMARY KEY (id),
	CONSTRAINT fk_verification_codes_users FOREIGN KEY(user_id) REFERENCES public.users(id)
); 
CREATE TABLE public.employee_confirmations( 
	id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
	employee_id integer NOT NULL,
	is_confirmed boolean NOT NULL,
	confirm_date Date NOT NULL,
	 CONSTRAINT pk_employee_confirmations PRIMARY KEY (id),
	CONSTRAINT fk_employee_confirmations_employees FOREIGN KEY(employee_id) REFERENCES public.employees(id)
);